# Generated by Django 3.2.7 on 2022-03-24 16:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('GameId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('LengthOfTime', models.IntegerField()),
                ('Genre', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Console', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Reviews', models.IntegerField(default=0)),
                ('Studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.studio')),
            ],
        ),
    ]
