# Generated by Django 4.0.3 on 2022-04-18 19:52

import django.contrib.postgres.fields
from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_lengthoftime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Console',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=game.models.get_default_arr, size=None),
        ),
    ]
