# Generated by Django 4.0.3 on 2022-04-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('game', '0003_alter_game_console'),
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='Game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='game.game'),
        ),
        migrations.AlterField(
            model_name='award',
            name='Organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='organization.organization'),
        ),
    ]
