# Generated by Django 3.2.7 on 2022-03-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('SName', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
